Project import generated by Copybara.
GitOrigin-RevId: 125c97feb29cd1b3677e76bba040a2cb6ad575dd

diff --git a/third_party/patches/rules_python.patch b/third_party/patches/rules_python.patch
--- a/third_party/patches/rules_python.patch
+++ b/third_party/patches/rules_python.patch
@@ -1,5 +1,5 @@
 diff --git python/private/attributes.bzl python/private/attributes.bzl
-index 8543caba..11f0d8d8 100644
+index c3b1cad..8d961a8 100644
 --- python/private/attributes.bzl
 +++ python/private/attributes.bzl
 @@ -443,6 +443,30 @@ be avoided if possible.
@@ -33,8 +33,23 @@ index 8543caba..11f0d8d8 100644
      },
  )
  
+diff --git python/private/interpreter_tmpl.sh python/private/interpreter_tmpl.sh
+index cfe85ec..31aceb6 100644
+--- python/private/interpreter_tmpl.sh
++++ python/private/interpreter_tmpl.sh
+@@ -16,6 +16,10 @@ set +e # allow us to check for errors more easily
+ readonly TARGET_FILE="%target_file%"
+ MAIN_BIN=$(rlocation "$TARGET_FILE")
+ 
++# Prevent Python packages installed in user site-packages outside of Bazel from being used;
++# e.g. this ensures the Pylance VS Code extension won't show IntelliSense for Python packages installed outside of Bazel
++export PYTHONNOUSERSITE=1
++
+ if [[ -z "$MAIN_BIN" || ! -e "$MAIN_BIN" ]]; then
+   echo "ERROR: interpreter executable not found: $MAIN_BIN (from $TARGET_FILE)"
+   exit 1
 diff --git python/private/normalize_name.bzl python/private/normalize_name.bzl
-index 7898222e..66d32050 100644
+index 7898222..66d3205 100644
 --- python/private/normalize_name.bzl
 +++ python/private/normalize_name.bzl
 @@ -47,7 +47,7 @@ def normalize_name(name):
@@ -47,10 +62,10 @@ index 7898222e..66d32050 100644
          return name
  
 diff --git python/private/py_executable.bzl python/private/py_executable.bzl
-index dd3ad869..9a723c57 100644
+index 9927975..8d51694 100644
 --- python/private/py_executable.bzl
 +++ python/private/py_executable.bzl
-@@ -1744,7 +1744,7 @@ def _create_providers(
+@@ -1795,7 +1795,7 @@ def _create_providers(
              ),
          ),
          create_instrumented_files_info(ctx),
@@ -59,7 +74,7 @@ index dd3ad869..9a723c57 100644
          PyExecutableInfo(
              main = main_py,
              runfiles_without_exe = runfiles_details.runfiles_without_exe,
-@@ -1817,7 +1817,7 @@ def _create_providers(
+@@ -1868,7 +1868,7 @@ def _create_providers(
      providers.extend(extra_providers)
      return providers
  
@@ -68,7 +83,7 @@ index dd3ad869..9a723c57 100644
      expanded_env = {}
      for key, value in ctx.attr.env.items():
          expanded_env[key] = _py_builtins.expand_location_and_make_variables(
-@@ -1826,6 +1826,32 @@ def _create_run_environment_info(ctx, inherited_environment):
+@@ -1877,6 +1877,32 @@ def _create_run_environment_info(ctx, inherited_environment):
              expression = value,
              targets = ctx.attr.data,
          )
@@ -102,7 +117,7 @@ index dd3ad869..9a723c57 100644
          environment = expanded_env,
          inherited_environment = inherited_environment,
 diff --git python/private/pypi/pkg_aliases.bzl python/private/pypi/pkg_aliases.bzl
-index 28d70ff7..b02eb342 100644
+index d71c37c..2d21abf 100644
 --- python/private/pypi/pkg_aliases.bzl
 +++ python/private/pypi/pkg_aliases.bzl
 @@ -157,26 +157,6 @@ def pkg_aliases(
@@ -150,10 +165,10 @@ index 28d70ff7..b02eb342 100644
          else:
              fail("The `actual` arg must be a dictionary or a string")
 diff --git python/private/pypi/simpleapi_download.bzl python/private/pypi/simpleapi_download.bzl
-index e8d7d094..886ee5eb 100644
+index a3ba969..069dfc1 100644
 --- python/private/pypi/simpleapi_download.bzl
 +++ python/private/pypi/simpleapi_download.bzl
-@@ -101,6 +101,7 @@ def simpleapi_download(
+@@ -102,6 +102,7 @@ def simpleapi_download(
                  attr = attr,
                  cache = cache,
                  get_auth = get_auth,
@@ -161,7 +176,7 @@ index e8d7d094..886ee5eb 100644
                  **download_kwargs
              )
              if hasattr(result, "wait"):
-@@ -154,7 +155,7 @@ def simpleapi_download(
+@@ -156,7 +157,7 @@ def simpleapi_download(
  
      return contents
  
@@ -170,7 +185,7 @@ index e8d7d094..886ee5eb 100644
      """Read SimpleAPI.
  
      Args:
-@@ -168,6 +169,7 @@ def _read_simpleapi(ctx, url, attr, cache, get_auth = None, **download_kwargs):
+@@ -170,6 +171,7 @@ def _read_simpleapi(ctx, url, attr, cache, get_auth = None, **download_kwargs):
                 http_file for docs.
          cache: A dict for storing the results.
          get_auth: A function to get auth information. Used in tests.
@@ -178,7 +193,7 @@ index e8d7d094..886ee5eb 100644
          **download_kwargs: Any extra params to ctx.download.
              Note that output and auth will be passed for you.
  
-@@ -212,7 +214,7 @@ def _read_simpleapi(ctx, url, attr, cache, get_auth = None, **download_kwargs):
+@@ -214,7 +216,7 @@ def _read_simpleapi(ctx, url, attr, cache, get_auth = None, **download_kwargs):
          url = [real_url],
          output = output,
          auth = get_auth(ctx, [real_url], ctx_attr = attr),
@@ -188,7 +203,7 @@ index e8d7d094..886ee5eb 100644
      )
  
 diff --git python/private/pypi/whl_repo_name.bzl python/private/pypi/whl_repo_name.bzl
-index 2b3b5418..66f6ace5 100644
+index 2b3b541..66f6ace 100644
 --- python/private/pypi/whl_repo_name.bzl
 +++ python/private/pypi/whl_repo_name.bzl
 @@ -58,8 +58,7 @@ def whl_repo_name(filename, sha256):
@@ -202,10 +217,10 @@ index 2b3b5418..66f6ace5 100644
  def pypi_repo_name(whl_name, *target_platforms):
      """Return a valid whl_library given a requirement line.
 diff --git python/private/python_bootstrap_template.txt python/private/python_bootstrap_template.txt
-index eb5595f4..d3478b54 100644
+index a979fd4..27614dc 100644
 --- python/private/python_bootstrap_template.txt
 +++ python/private/python_bootstrap_template.txt
-@@ -432,6 +432,17 @@ def _RunForCoverage(python_program, main_filename, args, env,
+@@ -440,6 +440,17 @@ def _RunForCoverage(python_program, main_filename, args, env,
  relative_files = True
  source =
  \t{source}
